In [1]:
import pandas as pd
import random
import numpy as np
#!pip install nltk
import nltk
import string
#nltk.download()
#!pip install sklearn
from sklearn.feature_extraction.text import TfidfVectorizer
from string import punctuation
#from nltk.corpus import stopwords
nltk.download('stopwords')
#from nltk.stem import WordNetLemmatizer 
#nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\cocoy\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [2]:
#Loading and Cleaning Data

#load in the csv contatining the data
df_original = pd.read_csv('wiki_movie_plots_deduped.csv')

In [3]:
#drop all rows in the dataframe that do not contain horror(1167) in genre catergory
df_horror=df_original.drop(df_original[df_original['Genre'] != 'horror'].index,inplace=False)
#drop columns we wont need
df_horror.drop(['Release Year','Origin/Ethnicity','Cast', 'Wiki Page','Director','Release Year'],axis=1, inplace = True)

#reduce horror to 1000 rows
df_horror=df_horror.sample(frac=1)
df_horror=df_horror.reset_index(drop=True)
df_horror_train=df_horror[0:1000]
df_horror_test=df_horror[1000:1167]

In [4]:
#drop all rows in dataframe that do not contain comedy(4379)
df_comedy=df_original.drop(df_original[df_original['Genre'] != 'comedy'].index, inplace = False)
df_comedy.drop(['Release Year','Origin/Ethnicity','Cast', 'Wiki Page','Director','Release Year'],axis=1, inplace = True)
#reduce horror to 1000 rows
df_comedy=df_comedy.sample(frac=1)
df_comedy=df_comedy.reset_index(drop=True)
df_comedy_train=df_comedy[0:1000]
df_comedy_test=df_comedy[1000:len(df_comedy)]

In [5]:
#merge the comedy and horror dataframes into one
df_HandC=pd.concat([df_horror_test,df_comedy_test])

#Pre punctuation parsing test
#df_HandC.iloc[1002]['Plot']

In [6]:
#Function to get rid of punctuation
def normalizeText(row):
    #create a list of punctuations we wish to delete
    punctuations = string.punctuation
    #change all letters to lower case
    row=row.lower()
    #loop through each word and get rid of punctuation and \r\n that came with data
    for x in row: 
        if x in punctuations: 
            row = row.replace(x, "")
        row = row.replace('\r\n', '')
    return row
#run the column through the normalizing function
df_HandC["Plot"] = df_HandC["Plot"].apply(normalizeText) 

In [7]:
#Post Punctuation Parsing test
#df_HandC.iloc[1002]['Plot']

In [8]:
##Prabesh being stupid. might be helpful?

vectorizer = TfidfVectorizer()
tfidf = vectorizer.fit_transform(df_HandC['Plot'])
#print similarity matrix
print((tfidf*tfidf.T).A)


[[1.         0.09913529 0.20150495 ... 0.15959985 0.10831577 0.04031809]
 [0.09913529 1.         0.08799101 ... 0.07258364 0.03701959 0.0157465 ]
 [0.20150495 0.08799101 1.         ... 0.13611337 0.08670981 0.04641494]
 ...
 [0.15959985 0.07258364 0.13611337 ... 1.         0.07771853 0.02571577]
 [0.10831577 0.03701959 0.08670981 ... 0.07771853 1.         0.01037378]
 [0.04031809 0.0157465  0.04641494 ... 0.02571577 0.01037378 1.        ]]


In [9]:
##Prabesh being stupid. might be helpful?

#deleting the punctuation
without_punct = [w for w in df_HandC['Plot'] if w not in punctuation]
#deleting stopwords like the/we/for
sw = stopwords.words('english')
without_sw = [w for w in without_punct if w not in sw]
#lemmatizing the plot summary
wnl = WordNetLemmatizer()
lemmatizedSummary = wnl.lemmatize(without_sw)



NameError: name 'stopwords' is not defined